### ISSUE TITLE
nodeschool may 2016

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#17]
http://nodeschool.io/international-day/

**Comment by gautamarora** [comment]
I've enrolled the nyc chapter for international day. Will go through the organizers tasks and make sure we are on top of what needs to be done.

**Comment by gautamarora** [comment]
@jovena @acingraham we should start planning something bigger & better for nodeschool international day :)

**Comment by acingraham** [comment]
Agreed!
