### ISSUE TITLE
Nodeschool Dallas Sticker Swap

### ISSUE THREAD

**Issue by michaeledavis-credera** [nodeschool/nyc#18]
Hi @gautamarora,

I'm one of the organizers for the [Nodeschool Dallas chapter](https://github.com/nodeschool/dallas), and I'll be in NYC this weekend + Monday. 

Would you like to meet up and do a Nodeschool sticker exchange? We've organized a few swaps on the [Organizers page](https://github.com/nodeschool/organizers/issues/182), and it's been really fun. Here's what our stickers look like: 
![nodeschool-dallas-skyline](https://cloud.githubusercontent.com/assets/5984944/12986261/e51ffe06-d0bb-11e5-85c2-bb8f884110a0.png)

**Comment by gautamarora** [comment]
Hi @michaeledavis-credera - this sounds like a great idea. I'm just seeing this message, and all the stickers are at my desk at work.

Can we exchange shipping addresses, and I can send you some NodeSchool NYC stickers via mail?

**Comment by michaeledavis** [comment]
Sounds great! 

Shoot me your shipping address at michaeledavis at outlook.com.

**Comment by gautamarora** [comment]
co-ordinating over email. closing here.
