### ISSUE TITLE
I'd like to host another Nodeschoo/NYC

### ISSUE THREAD

**Issue by hsin421** [nodeschool/nyc#2]
Is anyone with me? I'm fairly new to Node so this is the way I want to learn with everybody.

[NYCDA](http://nycda.com) will sponsor the event, providing classroom space and equipments.

I am updating Node 101/NYC event on 12/13 (Sat) under the nodeschool.io event page.

**Comment by gautamarora** [comment]
@hackygolucky could you close this issue as its probably served its purpose for that event.

**Comment by RBazelais** [comment]
Will do

On Tuesday, September 1, 2015, Gautam Arora <notifications@github.com>
wrote:

> @hackygolucky <https://github.com/hackygolucky> could you close this
> issue as its probably served its purpose for that event.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/nyc/issues/2#issuecomment-136907933>.
>


-- 
Best,
Rachel Bazelais
Host | Game Designer | Web Developer
Games, Seriously. Podcast <http://GamesSeriously.com>
Telephone #: (646)-496-6441
E-mail: Bazelais.rachel@gmail.com

**Comment by gautamarora** [comment]
Closing.
