### ISSUE TITLE
nodeschool contributors day

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#22]
We are thinking of hosting a nodeschool event focussed on giving back to the nodeschool community. The goal is to give students and mentors a focussed time and opportunity to:
1. create new workshops
2. submit PRs for existing workshops
3. create tools
4. translate workshops
5. design & build nodeschool nyc website
6. ...anything else

Starting this issue to figure out if this will be interesting and collect ideas. Would you be interested to attend such an the event, what support would you need?

**Proposed Ideas (extracted from list below):**
1. New Workshop: javascripting the hard way (@mmwtsn & @retrohacker)
2. New Workshop: learnyoudocker (@retrohacker)
3. New Workshop: learnyouredux (@gilchenzion & @ChrisMLee)
4. New Workshop: cheerio/jquery (@acingraham)
5. New Workshop: angular 1.x (@acingraham)
6. Tooling: workbook (@gautamarora)
7. Website: NYJS & NodeSchool NYC (@designMoreWeb)

**Comment by gautamarora** [comment]
cc @acingraham @designMoreWeb @mmwtsn @retrohacker @ChrisMLee @evelynStraigt @stefania11 @gilchenzion @amejias101 @cormickjbrowne @orangejulius @tapsboy

**Comment by gautamarora** [comment]
@mmwtsn @retrohacker - would this event help to get started on the new node workshop we were talking about? feel free to add more details on the idea.

**Comment by gautamarora** [comment]
cc @designMoreWeb for nodeschool-electron project. want to share details here?

**Comment by gautamarora** [comment]
cc @evelynStraigt for nodeschool spanish translation project

**Comment by yoshuawuyts** [comment]
This sounds like a heaps rad idea!

**Comment by retrohacker** [comment]
@gautamarora yes, absolutely! Carving out some time to sit down and focus on this would 100% help.

Let's do it! If the number of people who turn out is less than or equal to 8, I would be happy to host in Riverdale.

For background:

@mmwtsn and I were talking about two workshoppers:

* javascripting the hard way - Maxwell has noticed quite a few students are "pattern matching" for solutions. Where they aren't necessarily learning the meaning behind what they are typing, but what the general form of what a solution "looks" like. This is the most obvious when we help debug solutions like: `function(foo),bar {` where you can tell they know the visual form of a function statement, but not what the syntax represents. This workshopper would be a little more intense but would be in the style of the book series by the same name. It would try to dig deeper into the fundamentals and explain solutions line by line. It would be entirely experimental, we are unsure if this approach would be better or worse, but we would like to implement it and give it a try at the local nodeschool.
* learnyoudocker - A docker workshopper

**Comment by ismnoiet** [comment]
This is pretty good :+1:

**Comment by gilchenzion** [comment]
I'm looking into working on a learnyouredux if anyone is interested

**Comment by gautamarora** [comment]
thanks @yoshuawuyts & @ismnoiet !

**Comment by gautamarora** [comment]
@retrohacker @gilchenzion great ideas! I will check about hosting at conde nast as well.

**Comment by ChrisMLee** [comment]
@gilchenzion I'd be down to work on a learnyouredux

**Comment by acingraham** [comment]
Count me in!  I'd like to work on a cheerio/jQuery workshop.

**Comment by gautamarora** [comment]
I'd be working on the [workbook](https://github.com/gautamarora/workbook), [workbook-generator](https://github.com/gautamarora/workbook-generator) & [workbook-progress-tracker](https://github.com/gautamarora/workbook-progress-tracker) toolkit.

**Comment by gautamarora** [comment]
@acingraham that one is so needed! someone needs to do an angular one as well :)

**Comment by acingraham** [comment]
I could work on an Angular 1.x workshop

**Comment by Jovena** [comment]
@gautamarora LMK if Conde can't host and I'll find us another host. And, let's decide if we should collect RSVPs via Github or on an event page. Are you thinking timing of April or May so we have a bit of time to plan and get the word out?

**Comment by Jovena** [comment]
@andresdom Interested in joining us?

**Comment by gautamarora** [comment]
@Jovena I will keep you posted on hosting. I'm thinking of a mid-april timeline, probably a full day event vs a few hours. Continuing to use meetup for RSVPs is good, this thread is to get the event idea hashed out.

**Comment by designMoreWeb** [comment]
This is excellent. I am actually very excited for this. I can work on the website. I was thinking that we atleast try to do the wire frame and design language for the website prior to the day.

**Comment by evelynStraigt** [comment]
@caromedellin would be the one actually performing the translation work.

I like a lot of these ideas, I don't have anything else of my own at this time but I'd be happy to help with our existing ideas.

**Comment by gautamarora** [comment]
thanks @evelynStraigt. @caromedellin would you be interested in attending this event for translating some nodeschool workshops? we're planning it for around mid-april.

**Comment by caromedellin** [comment]
Yes I would be interested! I come back from Mexico the first day of April,
but I will be translating remotely.

2016-02-29 19:52 GMT-05:00 Gautam Arora <notifications@github.com>:

**Comment by caromedellin** [comment]
I do have one question, who would you guys prefer the naming of the files? 
es/README.md and problem.es.md
Or are there any other suggestions?

**Comment by gautamarora** [comment]
@caromedellin ok, this event is being planned as an in-person gathering. if you can join us on event day, that will be great as well. of course you can continue to work remotely on the translation project too. all contributions to nodeschool from our chapter are great.

Looking at the javascripting workshop, it seems the naming to follow is problem_es.md. You can see an example here: https://github.com/sethvincent/javascripting/tree/master/problems/introduction

**Comment by evelynStraigt** [comment]
@caromedellin - They are not all necessarily the same so I would look into the exercises folder, see the existing format, and then copy that format.  If a repository doesn't have any existing translations, it may be worth it to open an issue on the repository and ask the owner what format they would like.

**Comment by retrohacker** [comment]
Any progress on this? I'll be out of town the 13th - 24th of April :disappointed:

**Comment by gautamarora** [comment]
@retrohacker no progress yet on location and time, I will get back with some time options soon.

**Comment by designMoreWeb** [comment]
@gautamarora @acingraham Is there a way i can work on the Angular workshop with you?

**Comment by acingraham** [comment]
I haven't settled on working on Angular just yet, but if I do I'd be happy
to work with you!

**Comment by designMoreWeb** [comment]
Sounds good to me Andrew :)

**Comment by arjshiv** [comment]
@designMoreWeb I'd love to work on the angular 1.x course with you too!

**Comment by gautamarora** [comment]
This is finally happening folks!! https://github.com/nodeschool/organizers/issues/422

**Comment by gautamarora** [comment]
Closing this for now, we will restart this when the Merge into NodeSchool initiative gains traction.
