### ISSUE TITLE
Next event out of date on website & README.md

### ISSUE THREAD

**Issue by daniel-chung** [nodeschool/nyc#25]
The next event information is out of date on the:
- [website](http://nodeschool.io/nyc/) 
- [README](https://github.com/nodeschool/nyc/blob/master/README.md)

Here is the meetup link to the next event:
http://www.meetup.com/NY-JavaScript/events/227503383/

I can submit a PR for the README file, but I'm not sure where the website files are stored. Happy to help with updating the site if someone can point me in the right direction.

**Comment by gautamarora** [comment]
@daniel-chung thanks, i will update this now. will be glad to receive PRs for site updates.

**Comment by gautamarora** [comment]
@daniel-chung merged your PR and also brought the README up to date.
