### ISSUE TITLE
Is Nodeschool NYC dead?

### ISSUE THREAD

**Issue by mysterycommand** [nodeschool/nyc#26]
Hi, is this a dead project? I got really in to Nodeschool SF, and now that I've moved to New York would love to get this going again (looks like the last meetup was June of last year). I might be able to provide space (currently talking about logistics of that) but would be very curious to hear any insight as to why this seems to have fizzled out.

Also, anyone in here willing/interested in co-sponsoring a revival?

**Comment by hackygolucky** [comment]
@mysterycommand Howdy! NYJavaScript is helping keep it alive <3 https://www.meetup.com/NY-JavaScript/events/236674883/ @gautamarora is one of the folks doing that great work.

**Comment by gautamarora** [comment]
closing this issue as it is safe to conclude that nodeschool nyc is far from dead :)
