### ISSUE TITLE
Mentor Registration – March 19th, 2019

### ISSUE THREAD

**Issue by bnb** [nodeschool/nyc#32]
Hey everybody! 

![tenor](https://user-images.githubusercontent.com/502396/52672064-b119e500-2eea-11e9-8f3e-91cf990d1fcd.gif)

For our first refreshed event (5pm on March 19th @ [Microsoft](https://goo.gl/maps/akbY3gEoEow)), we're looking for mentors. If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (4:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @bernard-lin
- [x] @MylesBorins
- [x] @camdunne
- [x] @palante
- [x] @bfang212
- [x] @designMoreWeb
- [x] @brkwtz
- [x] @jpk1215
- [x] @amitlzkpa
- [x] @Jun-Yoo
- [ ] You?

Organizers:
- [x] @bnb
- [x] @fhinkel 
- [x] @joesepi
- [x] @johnelliott

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/nodeschoolnyc/events/258910478/

**Comment by bernard-lin** [comment]
Hi! I'd like to be a mentor, but this would be my first time

**Comment by MylesBorins** [comment]
Hi me please!

**Comment by bnb** [comment]
Awesome! Added both of you (@bernard-lin and @MylesBorins) to the list of mentors 👍

**Comment by bnb** [comment]
For what it's worth, if you could please be sure you're registered as an attendee on the Meetup page that would be extremely helpful 👍

**Comment by bernard-lin** [comment]
I'm registered 🙂

**Comment by camdunne** [comment]
Hi!! I would love to be a mentor! This would be my first time mentoring 😄

**Comment by bnb** [comment]
Awesome @camdunne! Would be fantastic to have you as a mentor. I see you've registered for the meetup, will add you to the mentor list 🙌

**Comment by tom-wagner** [comment]
Hi -- I would like to be a mentor as well! And it would be my first time!

**Comment by tom-wagner** [comment]
FYI @bnb, the title of this page/issue has the incorrect date. I believe it is Tuesday 3/19 not Saturday 3/16

**Comment by MylesBorins** [comment]
@bnb I just went to sign up on meetup and got waitlisted

**Comment by palante** [comment]
Hi, I'd like to be a mentor as well (first time). Signed up for the Meetup waitlist. Looking forward to it -- thanks!

**Comment by johnelliott** [comment]
Thanks @tom-wagner; updated date and time here.

**Comment by joesepi** [comment]
I'll mentor as well @bnb 🎉

**Comment by bfang212** [comment]
Hi, I'd like to be a mentor as well (first time).

**Comment by fhinkel** [comment]
So great to have you all as mentors ❤️ 

@tom-wagner Can you sign up on Meetup as well please. I think I got all other mentors off the waitlist. Let me know if I missed you.

**Comment by Jun-Yoo** [comment]
Hello, I'd like to be a mentor as well (first time).

**Comment by designMoreWeb** [comment]
I'll be able to mentor and i have mentored before

**Comment by jpk1215** [comment]
Hi I’d like to register. I have experience mentoring at Fullstack Academy. My email is jok1215@gmail.com.

**Comment by brkwtz** [comment]
i’d love to mentor! i build production microservices in node and teach js for code nation. first time nodeschool person. i’m on nodeschool’s waitlist under brkwtzr at gmail.

**Comment by amitlzkpa** [comment]
Hi, I'd like to be a mentor as well. I've mentored at CodeNation before.

**Comment by jpk1215** [comment]
Hi @fhinkel, checking in to see if the _confirmed mentor_ list is up to date? As of now should I plan on attending as a mentor?

**Comment by fhinkel** [comment]
Let me check with @bnb

**Comment by fhinkel** [comment]
@jpk1215, you're confirmed. Thank you!

**Comment by fhinkel** [comment]
@amitlzkpa Did you sign up on Meetup? I can't find you in the attendee list. Please tell us what your Meetup username is. Thanks!

**Comment by fhinkel** [comment]
@brkwtz You're confirmed. Thank you!

**Comment by fhinkel** [comment]
@designMoreWeb You're confirmed, thank you!

**Comment by fhinkel** [comment]
@bfang212 You're confirmed, thank you!

**Comment by fhinkel** [comment]
@tom-wagner Did you sign up on Meetup? I can't find you in the attendee list. Please tell us what your Meetup username is. Thanks!

**Comment by amitlzkpa** [comment]
@fhinkel Just registered on meetup as Amit Nambiar. Thanks.

**Comment by tom-wagner** [comment]
Hi @fhinkel -- somehow missed this. I am now registered but on the waitlist!

**Comment by Jun-Yoo** [comment]
@fhinkel I am unsure whether I am confirmed or not yet. I am signed up on Meetup.

**Comment by tom-wagner** [comment]
Unfortunately have to withdraw as I haven't completed the core workshops -- sorry!

**Comment by amitlzkpa** [comment]
Hi @fhinkel, checking in to see if the confirmed mentor list is up to date? As of now should I plan on attending as a mentor?

**Comment by fhinkel** [comment]
@amitlzkpa You're confirmed, thank you.

**Comment by fhinkel** [comment]
@tom-wagner , OK, no worries, maybe you can mentor next time. See you Tuesday!

**Comment by fhinkel** [comment]
@Jun-Yoo You're confirmed, thank you!

**Comment by fhinkel** [comment]
cc @crwilcox

**Comment by amitlzkpa** [comment]
@fhinkel I'm feeling a little unwell today. I won't be able to make it for today's workshop. Sorry for the last minute cancellation and hope to join for the next one!

**Comment by fhinkel** [comment]
Thanks everybody for helping!

@amitlzkpa No problem, hope you feel better. See you next time.
