### ISSUE TITLE
Mentor registration May 7th

### ISSUE THREAD

**Issue by fhinkel** [nodeschool/nyc#34]
Hey everybody! 

![tenor](https://user-images.githubusercontent.com/502396/52672064-b119e500-2eea-11e9-8f3e-91cf990d1fcd.gif)

For our next event (5pm on May 7th), we're looking for mentors. If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (4:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [ ] You?
- [ ] You?

Organizers:
- [x] @bnb
- [ ] @fhinkel 
- [x] @joesepi
- [x] @johnelliott

Thanks for joining! 🙌 

Please register on Meetup as well: https://www.meetup.com/nodeschoolnyc/events/260005249/

**Comment by bernard-lin** [comment]
I'm in!

**Comment by bernard-lin** [comment]
Just to double check, is this still on for tomorrow?

**Comment by johnelliott** [comment]
See you all tomorrow :)

**Comment by joesepi** [comment]
Thanks everyone. It was a great event!
