### ISSUE TITLE
Mentor registration July 9th

### ISSUE THREAD

**Issue by fhinkel** [nodeschool/nyc#40]
Hey everybody! 

![tenor](https://user-images.githubusercontent.com/502396/52672064-b119e500-2eea-11e9-8f3e-91cf990d1fcd.gif)

For our next event (5pm on July 9th), we're looking for mentors. If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (4:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @bernard-lin
- [x] @amitlzkpa
- [x] @taravancil
- [ ] @bfang212
- [ ] @kaicataldo 
- [ ] You?
- [ ] You?

Organizers:
- [x] @bnb
- [x] @fhinkel 
- [x] @joesepi
- [x] @johnelliott

Thanks for joining! 🙌 

Please register on Meetup as well: https://www.meetup.com/nodeschoolnyc/events/261514837

**Comment by bernard-lin** [comment]
I'll be there!

**Comment by amitlzkpa** [comment]
Me too!

**Comment by taravancil** [comment]
I’m in

**Comment by bfang212** [comment]
i'm in

**Comment by kaicataldo** [comment]
I'm interested in being a mentor!

**Comment by bnb** [comment]
@bfang212 @kaicataldo added both of you as mentors (in addition to @taravancil, @amitlzkpa,and @bernard-lin who we added a while ago)!

**Comment by kaicataldo** [comment]
I'm so sorry about the late notice, but I actually seem to be coming down with something and don't think I can make it tonight. I'll definitely try to sign up for the next one!

**Comment by taravancil** [comment]
^ Also so sorry for the late notice, it's a big launch day at work and I won't be able to attend.
