### ISSUE TITLE
September 10th

### ISSUE THREAD

**Issue by bnb** [nodeschool/nyc#47]
Hey everybody! 

![tenor](https://user-images.githubusercontent.com/502396/52672064-b119e500-2eea-11e9-8f3e-91cf990d1fcd.gif)

For our next event (event starts at 6pm on September 10), we're looking for mentors. If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (5:30) so we can get set up and have our mentor meeting.

Confirmed mentors:

- [x] @caiogondim
- [x] @msolano00 
- [ ] You?

Organizers:
- [x] @bernard-lin
- [x] @bnb
- [x] @fhinkel 
- [ ] @joesepi
- [x] @johnelliott

Thanks for joining! 🙌 

Please register on Meetup as well: https://www.meetup.com/nodeschoolnyc/events/262998868/

**Comment by bernard-lin** [comment]
I'll be there!

**Comment by caiogondim** [comment]
Would love to be a mentor :)

**Comment by bnb** [comment]
Sounds good. Added both of you!

**Comment by msolano00** [comment]
I know it is super late but I just discovered that the NYC chapter was active. If you need mentors I would happily help. I have been a previous mentor of the Costa Rica chapter.

**Comment by fhinkel** [comment]
@msolano00 Yes please!

**Comment by bnb** [comment]
@msolano00 if you’re still around we’d be more than happy to have you!

**Comment by JacopoDaeli** [comment]
@bernard-lin @bnb you can count me as mentor. Plz confirm.

**Comment by bernard-lin** [comment]
Hi @JacopoDaeli, thanks for volunteering! Unfortunately, we are not currently meeting right now because of the pandemic - this issue was for a meetup back in 2019. Please stay tuned for updates in the future.
