### ISSUE TITLE
questions about package.json

### ISSUE THREAD

**Issue by M0nica** [nodeschool/nyc#52]
I ran into a warning with`mustace` being listed in both dependencies and devDependencies and was wondering if both were required. 

```
"dependencies": {
    "mustache": "^2.2.1"
  },
  "devDependencies": {
   
    "mustache": "^2.3.0"
}
```

The warning was: 
```warning package.json: "dependencies" has dependency "mustache" with range "^2.2.1" that collides with a dependency in "devDependencies" of the same name with version "^2.3.0"```.

Also, the README says to run 

```bash
$ npm run docs:dev
```

but that command is no longer in the package.json. Should the command be re-added? or should people be instructed to just view static files after running `docs:build`?

**Comment by johnelliott** [comment]
Hey thanks Monica, It looks like we removed things that weren't strictly needed. I just made a little change to do the readme part.
