### ISSUE TITLE
Add new members to chapter team

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#6]
Please add @acingraham and me to the nyc chapter team.

This would allow us to contribute by editing the README (to add upcoming events) and create a new gh-pages branch for the nyc nodeschool site ([#5](https://github.com/nodeschool/nyc/issues/5))

**Comment by hackygolucky** [comment]
@acingraham @gautamarora Done! Look for invites possibly buried deep within the recesses of your inbox.

**Comment by acingraham** [comment]
Thanks Tracy and Gautam!
