### ISSUE TITLE
Update Readme for upcoming events

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#9]
I've updated the readme with info on upcoming events, created a new "past events" page to share details on all the past nodeschools and submitted a PR for it. https://github.com/nodeschool/nyc/pull/8

@acingraham @hackygolucky would you like to review PRs or are ok with me merging to master?

**Comment by acingraham** [comment]
I'm certainly okay with you merging to master

**Comment by gautamarora** [comment]
Thanks @acingraham.
